### ISSUE TITLE
How to set custom quality value when acquiring TIFF(jpeg) file

### ISSUE THREAD

**Issue by LizhuWeng** [dynarithmic/twain_library#11]
Hi,
I found it not work with custom quality setting by DTWAIN_SetJpegValues when acquiring file type with DTWAIN_TIFFJPEG.

**Comment by LizhuWeng** [comment]
It seems be related to the FreeImage API flag setting,
which found in CTIFFImageHandler::WriteGraphicFile in tiffun32.cpp

Any suggestion? Thanks.

**Comment by dynarithmic** [comment]
The PlugInTIFF provided by FreeImage currently doesn't handle the JPEG Quality.  I will see if I can adjust it so that it handles the jpeg quality.

**Comment by dynarithmic** [comment]
I will be closing this issue, since the DTWAIN_SetJpegValues is designed to only work for JPEG files, not TIFF files.
