### ISSUE TITLE
how to remove moiré patterns?

### ISSUE THREAD

**Issue by madeline799** [dynarithmic/twain_library#118]
Is this DTWAIN_SetCapValues API？how to set params?
what are these values?
DTWAIN_SOURCE | Source,
LONG | Capability,
LONG | SetType,
DTWAIN_ARRAY | CapValues

**Comment by dynarithmic** [comment]
What computer language are you using?  If you are using C or C++, please see [this example](https://github.com/dynarithmic/twain_library/blob/master/demos/c/GetSetCapabilities/GetSetCapabilities.c) and others that call DTWAIN_SetCapValues. 

In addition, see the [help](https://www.dynarithmic.com/onlinehelp/dtwain/newversion/ExampleSettingDeviceCapabilites.html) documentation.

**Comment by dynarithmic** [comment]
Closing ticket.  Not able to duplicate and no follow-up.
