### ISSUE TITLE
save file to disk immediately after acquire one page

### ISSUE THREAD

**Issue by leetb-leetb** [dynarithmic/twain_library#133]
hi，call DTWAIN_AcquireFileEx to get files, such as 3 numPages;  is there an option to set acquire one page and save file to disk immediately ? not acquire all pages completed and save files to disk . it seems that my driver not supported the Job Control, and I can't found the option on API Document

**Comment by dynarithmic** [comment]
See the [DTWDEMO32](https://github.com/dynarithmic/twain_library/blob/d1f50b1ac63a53f6aa38edb7bb72b7bc8bc9a3c4/demos/c/FullDemo/dtwdemo.c#L1337) program and the call to [DTWAIN_GetCurrentAcquiredImage](https://www.dynarithmic.com/onlinehelp/dtwain/newversion/DTWAIN_GetCurrentAcquiredImage.html).  You will need to know how to handle the DIB data yourself -- you can save it to a file, but you need to be familiar with creating the BMP header.

**Comment by leetb-leetb** [comment]
thanks！
