### ISSUE TITLE
How can i use this  library with NodeJS

### ISSUE THREAD

**Issue by pengkid-rgb** [dynarithmic/twain_library#22]

**Comment by dynarithmic** [comment]
There really is nothing special about DTWAIN.  The DTWAIN library is a plain Windows DLL, and can be used by any language with the ability to call exported DLL functions.

Unfortunately I do not know NodeJS to answer your question.  If you know how to get NodeJS to interface to any DLL (not just this one) and call exported functions, that will be the way to use this library.  

Probably you should ask a NodeJS-centric group of programmers and ask in general, how do I get NodeJS to call exported DLL functions.

**Comment by pengkid-rgb** [comment]
Thanks，now i know how to use. i will close this issue

**Comment by pengkid-rgb** [comment]
use node-addon-api !
