### ISSUE TITLE
Java JNI stuck on AVISION AV830Plus scanner

### ISSUE THREAD

**Issue by ananas-hebo** [dynarithmic/twain_library#32]
java stuck at "DTWAIN_AcquireFile",  a dialog show from the scanner driver.

![image](https://user-images.githubusercontent.com/5362672/167803520-b485ec4c-7e16-4625-b8bc-00ccab4af109.png)

```java
public class SimpleAcquire2 {
	public void SimpleTest() throws Exception {
		DTwainJavaAPI api = new DTwainJavaAPI(DTwainJavaAPI.JNIDLLName_64U);
		api.DTWAIN_JavaSysInitialize();
		api.DTWAIN_SetTwainLog(DTwainJavaAPIConstants.DTWAIN_LOG_ALL, "twain.log");

		long TwainSource = api.DTWAIN_SelectSource();
		if (TwainSource != 0) {
			int status = api.DTWAIN_AcquireFile(TwainSource, "test.png", DTwainFileType.FILETYPE_PNG,
					DTwainJavaAPIConstants.DTWAIN_USELONGNAME, DTwainJavaAPIConstants.DTWAIN_PT_DEFAULT, 1, false,
					false);
			System.out.println(status);
		}
		api.DTWAIN_JavaSysDestroy();
	}

	public static void main(String[] args) {
		SimpleAcquire2 s = new SimpleAcquire2();
		try {
			s.SimpleTest();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
```
[twain.log.zip](https://github.com/dynarithmic/twain_library/files/8667993/twain.log.zip)

**Comment by ananas-hebo** [comment]
if remove  

```
api.DTWAIN_SetTwainLog(DTwainJavaAPIConstants.DTWAIN_LOG_ALL, "twain.log");
```
the error is gone. DTWAIN_AcquireFile return 1000.
But NO output file.

**Comment by dynarithmic** [comment]
Please make sure you are looking in the correct location for "test.png".  

I would suggest to give a full path name, to verify that the file actually exists.

**Comment by ananas-hebo** [comment]
@dynarithmic  thanks for your replay.


```

public class SimpleAcquire2 {
	public void SimpleTest() throws Exception {
		DTwainJavaAPI api = new DTwainJavaAPI(DTwainJavaAPI.JNIDLLName_64U);
		api.DTWAIN_JavaSysInitialize();
//		api.DTWAIN_SetTwainLog(DTwainJavaAPIConstants.DTWAIN_LOG_ALL, "twain.log");

		long TwainSource = api.DTWAIN_SelectSource();
		if (TwainSource != 0) {
			int status = api.DTWAIN_AcquireFile(TwainSource, "D:\\test.bmp", DTwainFileType.FILETYPE_BMP,
					DTwainJavaAPIConstants.DTWAIN_USELONGNAME, DTwainJavaAPIConstants.DTWAIN_PT_BW, 1, false, false);
			System.out.println(status);
		}
		api.DTWAIN_JavaSysDestroy();
	}

	public static void main(String[] args) {
		SimpleAcquire2 s = new SimpleAcquire2();
		try {
			s.SimpleTest();
		} catch (Exception e) {

			e.printStackTrace();
		}

		System.out.println("OK");
	}
}
```

output:

```
dtwainjni64u
1000
OK

```

I fix the path of the file,  but still no output file.

**Comment by dynarithmic** [comment]
Please run the DTWDEMO64u.exe program to determine if this is an issue with DTWAIN itself, or a Java/JNI issue.   Right now it is impossible to tell what the issue is by looking at your Java code.

If the image can be acquired successfully using DTWAINO64u, then the underlying issue is with the Java layer in some way.  

Having said that, we are looking to overhaul the entire Java layer and utilize a new interface to the DLL through JNI.

**Comment by ananas-hebo** [comment]
@dynarithmic 

i try DTWDEMO64u.exe

![image](https://user-images.githubusercontent.com/5362672/168581790-bc02f762-440f-446e-b7f4-cb8385548da9.png)

Acquire Native, Buffered, File is failed.
![image](https://user-images.githubusercontent.com/5362672/168582481-e7e38983-2fa7-42b0-9e2e-b690dd5e0e4e.png)

Acquire File(Source Mode)  like ok, get a tmp file:
![image](https://user-images.githubusercontent.com/5362672/168582800-6e65af4a-8658-447c-b6c6-d5d606e3a1df.png)

I change my code use "DTWAIN_USELONGNAME" :

```
int status = api.DTWAIN_AcquireFile(TwainSource, "D:\\test.bmp", DTwainFileType.FILETYPE_BMP,
					DTwainJavaAPIConstants.DTWAIN_USELONGNAME + DTwainJavaAPIConstants.DTWAIN_USESOURCEMODE,
					DTwainJavaAPIConstants.DTWAIN_PT_BW, 1, false, false);
// but status return -1
```

**Comment by dynarithmic** [comment]
You can generate a log from DTWDEMO by selecting logging from the main menu.  Please do that, as it seems there is something very strange about the device you are using.  

Also, using "source mode" is only available if your device itself supports the file type.  You shouldn't use it unless you are certain that your device supports acquiring to BMP files.  The list of file types can be retrieved by calling [DTWAIN_IsFileXferSupported](http://www.dynarithmic.com/onlinehelp5/dtwain/dtwain_isfilexfersupported.htm).

**Comment by ananas-hebo** [comment]
@dynarithmic 

I test "TWACKER" AND [twain-samples](https://github.com/twain/twain-samples/tree/master/releases/Twain_App_sample01_02040100).

If choose output to a file are failed, but change to native is OK.
![image](https://user-images.githubusercontent.com/5362672/168722784-834ee5d1-1c78-41a3-b025-bdefe6bfb2dc.png)

I test DTWDEMO with "native",  NO image like this: 
![image](https://user-images.githubusercontent.com/5362672/168721150-05bcb60f-5e35-4c45-a486-6a457bda3fbc.png)

Use java API got a error.
``` java
public class SimpleAcquire4 {
	public void SimpleTest() throws Exception {
		DTwainJavaAPI api = new DTwainJavaAPI(DTwainJavaAPI.JNIDLLName_64U);
		api.DTWAIN_JavaSysInitialize();
		// api.DTWAIN_SetTwainLog(DTwainJavaAPIConstants.DTWAIN_LOG_ALL, "twain.log");

		long TwainSource = api.DTWAIN_SelectSource();
		if (TwainSource != 0) {
			DTwainAcquisitionArray array = api.DTWAIN_AcquireNative(TwainSource,
					DTwainJavaAPIConstants.DTWAIN_PT_DEFAULT, 1, false, false);
			System.out.println(array);
		}
		api.DTWAIN_JavaSysDestroy();
	}

	public static void main(String[] args) {
		SimpleAcquire4 s = new SimpleAcquire4();
		try {
			s.SimpleTest();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}


dtwainjni64u
com.dynarithmic.twain.DTwainJavaAPIException: Unrecoverable error in DTWAINJavaAPI.DLL
	at com.dynarithmic.twain.DTwainJavaAPI.DTWAIN_AcquireNative(Native Method)
	at com.dtwain.test.SimpleAcquire4.SimpleTest(SimpleAcquire4.java:16)
	at com.dtwain.test.SimpleAcquire4.main(SimpleAcquire4.java:26)

```

I think dtwain has something wrong?

**Comment by dynarithmic** [comment]
As mentioned previously, please turn on the logging in the DTWDEMO program.  Since I do not have your device, it is impossible to diagnose the issue until a log is presented.

**Comment by ananas-hebo** [comment]
Wait a few days, I'm quarantined by COVID-19.

**Comment by ananas-hebo** [comment]
I test on "Canon DR-G1100"  and "Panasonic KV-SL1077/66/56 MK2" work well.
"AVISION AV830Plus" has issues  itself.
