### ISSUE TITLE
JNI without "GetPixelType"

### ISSUE THREAD

**Issue by ananas-hebo** [dynarithmic/twain_library#35]
I can't find this method in jni.

How to get the current Pixel Type (Color) setting?

The DTWAIN_GetPixelType function gets the current Pixel Type (Color) and Bit Depth (Bits Per Pixel) that will be used when acquiring an image.

```c
DTWAIN_BOOL DTWAIN_GetPixelType
```

**Comment by dynarithmic** [comment]
Try: 

`DTWAIN_GetCapValuesInt(source, DTwainCapabilityHandler.ICAP_PIXELTYPE,  DTwainJavaAPIConstants.DTWAIN_CAPGETCURRENT);`

In general, any capability can be retrieved using the family of function that are named DTWAIN_GetCapValues...().   The capabilities can be found in the [Twain Specification](https://github.com/dynarithmic/twain_library/blob/master/TwainSpecification/TWAIN-2.4-Specification.pdf).
