### ISSUE TITLE
Need to clear acquisition array during scan

### ISSUE THREAD

**Issue by nswdxqq** [dynarithmic/twain_library#45]
I'm evaluating the library for a scan project, and facing one problem with image acquisition as follows:

    I need to acquire many images from scanner with one scan process;
    I'm using buffered transfer from scanner;
    During scanning a file for each image is created and the DIB is not needed anymore once the file is saved;
    The memory keeps increasing during scanning and the program is out of memory finally;
    So I'm curious if there is any way to clear the array of acquisition during scanning? And I'm using C# by the way.

**Comment by dynarithmic** [comment]
See the [DTWDEMO.c](https://github.com/dynarithmic/twain_library/blob/master/demos/c/dtwdemo/dibdisplay.c) program.  Look specifically at the DTWAIN_TN_QUERYPAGEDISCARD notification:

```cpp
		/* See if we want to keep the DIB */
		case DTWAIN_TN_QUERYPAGEDISCARD:
```
Note that we get the current DIB and display it in a preview window.  This notification is sent for every page acquired.  

What you can do is copy the DIB data by calling `DTWAIN_GetCurrentAcquiredImage`, save that data in the way that you desire, and on return of the notification, the return value would be 0.

So an outline could be something like this.

```cpp
		/* See if we want to keep the DIB */
		case DTWAIN_TN_QUERYPAGEDISCARD:
                {
                    HANDLE h = DTWAIN_GetCurrentAcquiredImage(Your_Data_Source);
                    YourFunctionToSaveBitmapDataToFile(h);
                    return 0;  // This will discard the original DIB data
                 }
```

**Comment by dynarithmic** [comment]
Also, take a look at [DTWDEMO.C](https://github.com/dynarithmic/twain_library/blob/master/demos/c/dtwdemo/dibdisplay.c) and the `DTWAIN_TN_QUERYPAGEDISCARD` notification.

```cpp
		case DTWAIN_TN_QUERYPAGEDISCARD:
		{
			LRESULT retVal;
			HANDLE h = DTWAIN_GetCurrentAcquiredImage();
                        // Save the handle returned by DTWAIN_GetCurrentAcquiredImage
                        // ...
                        return 0; // throw the original DIB away
		}
```
See if something like this will work for you.

**Comment by nswdxqq** [comment]
OK, seems DTWAIN_TN_QUERYPAGEDISCARD works, need more evaluation, thanks!
