### ISSUE TITLE
How to set up Paper ejection direction?

### ISSUE THREAD

**Issue by CapacitorDev** [dynarithmic/twain_library#49]
Hi, 
my scan has two ejection forward and backward.

any one know how to set up it by using code C#?

thank you!

**Comment by dynarithmic** [comment]
I am not sure I know what "paper ejection" means, but it does not sound like a standard TWAIN capability. 

1) What is the name of the device?

2) If it is a custom TWAIN capabilty, you will need to know which one it is and set it using DTWAIN_SetCapValues.  For this, it requires that you know from the manufacturer if custom capabilties are supported, which one it is.

**Comment by CapacitorDev** [comment]
hi @dynarithmic , thank you for the reply.

"paper ejection" --> when you open with UI, you will see this setting.
![paper_ejection](https://user-images.githubusercontent.com/90281097/228116767-2e43e876-b1da-4bd8-9460-c4c49f973f5d.JPG)


I want the code let the paper forward out of the scanner after scanning. ( not return backward the paper, it  occurs Paper Jam a lot this way )

1. What is the name of the device? --> plustek MobiOffice D600 Plus
2. Seems like it's not a standard TWAIN CAP. I will do more research about this DTWAIN_SetCapValues

**Comment by dynarithmic** [comment]
If you run the DTWDEMO.exe program, select the source, you can get a listing of the capabilities if you choose **Source Properties...** from the main menu **Source Selection Test**.  

If you see capabilities named **CAP_CUSTOMBASE + xxxx**, those are the custom capabilities.

**Comment by dynarithmic** [comment]
DTWAIN does not know what those capabilities do, what data type they are (string, booleans, integers, etc.), and whether they can be set (some may be read-only).

You will need to get the custom capability information from the manufacturer as to the data type, container used to store the information, etc.   Once you get this information, you would call DTWAIN_GetCapValuesEx() specifying the container to use and data type.

**Comment by dynarithmic** [comment]
[See DTWAIN_GetCapValuesEx2](https://www.dynarithmic.com/onlinehelp/dtwain/newversion/DTWAIN_GetCapValuesEx2.html).  Once you get the information about the capability, use this function.

**Comment by dynarithmic** [comment]
[Make sure you are using the latest version of DTWAIN](https://github.com/dynarithmic/twain_library/releases), as many changes have occurred since then.  

You can also try the new `DTWAIN_TestGetCaps` introduced in version 5.5.0 (see the [updates.txt](https://github.com/dynarithmic/twain_library/blob/master/updates/updates.txt) on how to use this function.  This function can be used to test the custom capabilities using all the container and data types. 

I will be closing this ticket, and will only reopen if there still is an issue.
