### ISSUE TITLE
Connecting to the scanner via a network

### ISSUE THREAD

**Issue by HezinTUKE** [dynarithmic/twain_library#86]
I have a scanner to which I connect via the network, but TWAIN does not see it. Is it possible that TWAIN doesn’t have such an option or could it be me who is making a mistake in code ?

**Comment by dynarithmic** [comment]
How do you connect to the scanner over the network?  The scanner should have a TWAIN driver that you installed locally that can detect the scanner over the network, thus expose the product name within the "Select Source" dialog box when selecting a scanner.

The Hewlett-Packard all-in-one scanner/printers has such an interface (for example, the HP MFP M277 has this).  

Also, please check whether the driver is 32-bit or 64-bit.  If the TWAIN driver is 32-bit, then you must use the dtwain32 series of DLL's.  If the driver is 64-bit, then you must use the dtwain64 series of DLL's.
