### ISSUE TITLE
How to Disable the Scanning Window During Image Acquisition?

### ISSUE THREAD

**Issue by handrenmuhammad** [dynarithmic/twain_library#87]
I want to disable this UI during the scanning process, but I couldn't find any relevant information in the documentation.
Is there a way to hide this UI?

![blob](https://github.com/dynarithmic/twain_library/assets/69752743/f75d47cd-85ab-4784-9169-47a768e79c0a)

**Comment by dynarithmic** [comment]
There is no guarantee this will work, since this is highly dependent on the TWAIN data source, but you can try [DTWAIN_EnableIndicator](https://www.dynarithmic.com/onlinehelp/dtwain/newversion/DTWAIN_EnableIndicator.html)

**Comment by handrenmuhammad** [comment]
Thanks for your help, it worked
